### ISSUE TITLE
테스트1

### ISSUE THREAD

**Issue by hjlee83** [sophiee23/hi-springboot#1]
@sophiee23 스프링부트를 돌려보고 화면을 캡쳐한후 댓글에 넣어보삼

**Comment by sophiee23** [comment]
![image](https://cloud.githubusercontent.com/assets/25605115/22720085/232dc55e-edec-11e6-8f56-1226a58ef466.png)
@hjlee83

**Comment by hjlee83** [comment]
@sophiee23 pom.xml에서 security 부분 주석 처리해보삼.

**Comment by sophiee23** [comment]
@hjlee83 인증팝업은 없어졌어요.
![image](https://cloud.githubusercontent.com/assets/25605115/22720252/05ca33f2-eded-11e6-969b-7989e88f218e.png)

**Comment by sophiee23** [comment]
@hjlee83 
e028dcdb2e0b648e187eeed32319dcac6d302dc1

**Comment by hjlee83** [comment]
@sophiee23 잘했삼.
