### ISSUE TITLE
게시판 RESTFUL - GET만들기

### ISSUE THREAD

**Issue by hjlee83** [sophiee23/hi-springboot#2]
게시판 RESTFUL 만들기

**Comment by sophiee23** [comment]
@hjlee83 thymeleaf에서 템플릿이 없다는 에러발생합니다 ㅠㅠ
![image](https://cloud.githubusercontent.com/assets/25605115/22724919/f9b66444-ee0c-11e6-90e2-23fdce190db3.png)
![image](https://cloud.githubusercontent.com/assets/25605115/22724934/0e7767ac-ee0d-11e6-9ccb-accfa02d9819.png)

**Comment by hjlee83** [comment]
Article 도메인을 만드세요.

private long id;
private String title;
private String description;

GET 호출로 Article에 내용을 넣어서 화면에 띄우세요.
화면 캡쳐

**Comment by sophiee23** [comment]
@hjlee83 도메인 toString해서 뿌렸어요
![image](https://cloud.githubusercontent.com/assets/25605115/22726669/0e55df3c-ee18-11e6-8c60-5347696554c6.png)
